import { createSlice } from "@reduxjs/toolkit";

const initialState={
    value:0
}
// Create a slice of the Redux store for the counter feature, defining the initial state and reducers for incrementing, decrementing, and incrementing by a specific amount
const counterSlice=createSlice({
    name:"counter",
    initialState,
    reducers:{
        increment:(state)=>{
            state.value+=1;
        },
        decrement:(state)=>
        {
            state.value-=1;
        },
        incrementByAmount:(state,action)=>
        {
            state.value+=action.payload;
        }
    }
})

// Export the action creators generated by createSlice and the reducer function to be used in the Redux store configuration
export const {increment,decrement,incrementByAmount}=counterSlice.actions;
export default counterSlice.reducer;